# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=1.0
maven_group=com.papack
archives_base_name=BootsLunge-fabric26.2
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.155.0+26.2
# Mod Menu
modmenu_version=20.0.1